### PR TITLE
Added IP2Location.io endpoint to get external IP

### PR DESCRIPTION
**Pull request by ip2location**

### CODE REVIEW

**Review by mellon85 — APPROVED** [review]

**Comment by mellon85** [comment]
@ip2location the repo requires commits to be signed

**Comment by ip2location** [comment]
It should be signed now.

**Comment by mellon85** [comment]
you should do

```
# remote the last commit you added
git reset --hard dda46ef9883de47ab51b7b1b0ad15d6024a13c87
# sign the first commit you created
git commit --amend --signoff
# push it upstream replacing the previous one
git push --force
```

**Comment by ip2location** [comment]
Have done as you've requested.

**Pull request merged**
